### ISSUE TITLE
[Feature Request] Consider using Transparent background color instead of Chroma keying the background

### ISSUE THREAD

**Issue by ArcadeArchie** [SpaceCowboyLive/joyviz#3]
Stream overlay provider's like Streamelements or Streamlabs do this since Chromakeying the Background artifacts the Text very badly.

how it looks right now
![image](https://github.com/SpaceCowboyLive/joyviz/assets/29282748/a0f6a880-18f6-4bd9-85c8-8637d95e39a9)

setting the Background to a transparent color (and removing the Chroma key filter)
![image](https://github.com/SpaceCowboyLive/joyviz/assets/29282748/02101b03-a498-456c-98bf-9b868a28e4f2)

**Comment by cprn** [comment]
In OBS you can use custom CSS, or just put that in the HTML file itself:
```css
body { background-color: rgba(0, 0, 0, 0); margin: 0px auto; overflow: hidden; }
```
